name: flutter_splash_tizen
description: A new flutter plugin project.
version: 0.1.0
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/flutter_splash_tizen

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^5.3.1
  yaml: ^3.1.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  