name: flutter_blue_tizen_example
description: Demonstrates how to use the flutter_blue_tizen plugin.
publish_to: "none"

environment:
  flutter: ">=2.0.0"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.1.3
  flutter_blue_tizen:
    path: ../

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  integration_test_tizen:
    path: ../../integration_test/

flutter:
  uses-material-design: true
