name: flutter_blue_tizen
description: Tizen implementation of flutter_blue plugin
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/flutter_blue
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: FlutterBlueTizenPlugin
        fileName: flutter_blue_tizen_plugin.h
